data_path: 'data/rmsf_atlas_data_prottransready.txt'
fasta_path: 'data/atlas_sequences.fasta'
enm_path: 'data/atlas_minimized_fluctuations_ANM.jsonl'
splits_path: 'data/atlas_splits.json'
batch_size: 4
epochs: 100
save_steps: 528
add_pearson_loss: False
add_sse_loss: False
enm_embed_dim: 512
enm_att_heads: 8
num_layers: 2
kernel_size: 3
mixed_precision: False
gradient_accumulation_steps: 1

#TODO: keep as args
run_name: None
adaptor_architecture: null