data_path: 'data/rmsf_atlas_data_prottransready.txt'
fasta_path: 'data/atlas_sequences.fasta'
enm_path: 'data/atlas_minimized_fluctuations_ANM.jsonl'
splits_path: 'data/atlas_splits.json'
batch_size: 4
epochs: 100
add_pearson_loss: False
add_sse_loss: False
enm_embed_dim: 128
enm_att_heads: 8
num_layers: 3
kernel_size: 5
mixed_precision: False
gradient_accumulation_steps: 1
seed: 42
adaptor_architecture: null
run_name: null
num_labels: 1 # for regression
dropout_rate: 0.2

#huggingface trainer arguments
training_args:
  output_dir: './results/results_{run_name}_{timestamp}'
  run_name: null  # This will be set programmatically
  evaluation_strategy: 'steps'            
  save_strategy: 'steps'
  load_best_model_at_end: True         # Load the best model (based on metric) at the end of training
  metric_for_best_model: 'spearmanr'    # The metric to use to compare models
  greater_is_better: True               # Defines whether higher values of the above metric are better
  learning_rate: 0.0003
  save_safetensors: False
  save_steps: 256
  save_total_limit: 3
  logging_strategy: 'epoch'

inference_args:
  device: 'cuda:0'
  seq_model_path: ./models/weights/flexpert_seq_weights.bin
  3d_model_path: ./models/weights/flexpert_3d_weights.bin
  enm_type: 'ANM'
