wandb_version: 1

data_path:
  desc: null
  value: data/rmsf_atlas_data_prottransready.txt
run_name:
  desc: null
  value: debug
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 2
save_steps:
  desc: null
  value: 528
add_pearson_loss:
  desc: null
  value: false
add_sse_loss:
  desc: null
  value: false
fasta_path:
  desc: null
  value: data/atlas_sequences.fasta
enm_path:
  desc: null
  value: data/atlas_minimized_fluctuations_ANM.jsonl
splits_path:
  desc: null
  value: null
adaptor_architecture:
  desc: null
  value: no-adaptor
enm_embed_dim:
  desc: null
  value: 512
enm_att_heads:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 2
kernel_size:
  desc: null
  value: 3
mixed_precision:
  desc: null
  value: false
gradient_accumulation_steps:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729777480.410653
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
